In [ ]:
import numpy as np

numpy :package for multidimensionality array

In [3]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [4]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
sample_matrix=np.array(list_of_lists)

In [5]:
sample_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(18)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [10]:
np.arange(1,46,4)

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45])

In [12]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [13]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.ones(100,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [17]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [18]:
np.zeros((2,10),int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [19]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [20]:
np.linspace(0,14,4)

array([ 0.        ,  4.66666667,  9.33333333, 14.        ])

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.random.rand(3,2)

array([[0.70100585, 0.32048274],
       [0.15160654, 0.76636415],
       [0.24279189, 0.01612281]])

In [27]:
np.random.randn(3,2)

array([[ 0.3854553 ,  0.32792027],
       [ 0.27704467,  0.81308104],
       [ 0.55906658, -1.29345478]])

In [32]:
np.random.randint(1,5)

3

In [33]:
np.random.randint(34,100,50)

array([70, 91, 34, 70, 77, 89, 97, 40, 95, 38, 88, 40, 83, 78, 49, 63, 38,
       86, 44, 42, 79, 59, 90, 40, 56, 79, 78, 97, 54, 90, 60, 45, 51, 56,
       53, 59, 92, 56, 71, 35, 40, 63, 93, 61, 93, 82, 89, 83, 51, 36])

In [35]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [36]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [38]:
rand_array=np.random.randint(0,100,20)
rand_array

array([36, 25, 82, 84, 38, 14,  1, 53,  1, 23, 36, 80, 90, 43, 31, 98, 81,
       32, 30, 46])

In [42]:
rand_array.min()

1

In [43]:
rand_array.argmin()

6

In [44]:
sample_array.dtype

dtype('int32')

In [46]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [49]:
a=np.random.rand(2,3)
a

array([[0.11994358, 0.00716758, 0.15414699],
       [0.64794681, 0.20113499, 0.61566287]])

In [50]:
a.T

array([[0.11994358, 0.64794681],
       [0.00716758, 0.20113499],
       [0.15414699, 0.61566287]])

In [53]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [54]:
sample_array[3]

13

In [55]:
sample_array[1:7]

array([11, 12, 13, 14, 15, 16])

In [56]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [57]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [58]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [60]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [61]:
subset_sample_array[1:4]=1001
subset_sample_array

array([  10, 1001, 1001, 1001,   14,   15,   16])

In [62]:
subset_sample_array[:]

array([  10, 1001, 1001, 1001,   14,   15,   16])

2D array

In [ ]:
import numpy as np


In [64]:
sample_matrix=np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [67]:
sample_matrix[0:2,2]

array([ 1, 21])

In [68]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [69]:

sample_matrix[2]

array([56, 76, 24,  7])

In [70]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

In [72]:
sample_array=np.arange(1,20)

In [73]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [74]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [75]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [76]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [77]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [78]:
np.max(sample_array)

19

In [79]:
np.min(sample_array)

1

In [80]:
np.argmax(sample_array)

18

In [81]:
np.argmin(sample_array)

0

In [82]:

np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361], dtype=int32)

In [83]:
np.std(sample_array)

5.477225575051661

In [84]:
np.var(sample_array)

30.0

In [88]:
np.mean(sample_array)

10.0

In [94]:
array=np.random.randn(3,4)
array

array([[ 0.11799965,  1.29655131, -0.59615054, -0.09891911],
       [ 0.24342808, -0.3043838 ,  0.08902343, -1.276527  ],
       [-0.07813035, -0.01102057,  0.56167461, -0.17538413]])

In [95]:
np.round(array,decimals=3)

array([[ 0.118,  1.297, -0.596, -0.099],
       [ 0.243, -0.304,  0.089, -1.277],
       [-0.078, -0.011,  0.562, -0.175]])

In [96]:
sports=np.array(['golf','cricket','football','bb','bb'])
np.unique(sports)

array(['bb', 'cricket', 'football', 'golf'], dtype='<U8')